title: Concepts in Physical Chemistry
description: A collection of course notes created by Fall 2025 CH730 (Advanced Physical Chemistry) students at NCSU.
theme: just-the-docs

url: https://oreaganowombat.github.io/CH730-Fall25

math: mathjax

color_scheme: custom-scheme

aux_links:
  Source Code: https://github.com/oREAGanoWombat/CH730-Fall25

plugins:
  - jekyll-default-layout

favicon_ico: "images/site-logo.png"

search_enabled: true