title: Concepts in Physical Chemistry
description: A collection of course notes created by Fall 2025 CH730 (Advanced Physical Chemistry) students at NCSU.
remote_theme: pmarsceill/just-the-docs
theme: just-the-docs

math: mathjax

color_scheme: custom-scheme

aux_links:
  Source Code: https://github.com/oREAGanoWombat/CH730-Fall25

favicon_ico: "images/site-logo.png"
